package view;

// Bibliotecas necessárias
import model.AtividadeModel; // Model
import controller.AtividadeController; // Controller
import java.util.ArrayList; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caior
 */

// AtividadeView é um JInternalFrame
public class AtividadeView extends javax.swing.JInternalFrame {
    
    // Inicializando componentes
    private int linha = -1; // Atributo contagem para setar valores no JtTable
    public AtividadeView() {
        // Métodos
        initComponents();
        preencherTabela();
        inicializa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxDecoracao1 = new javax.swing.JTextField();
        JpAtividade = new javax.swing.JPanel();
        jlResponsavel = new javax.swing.JLabel();
        jlMusico = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAtividade = new javax.swing.JTable();
        jlDescricao = new javax.swing.JLabel();
        jlGenero = new javax.swing.JLabel();
        jlBuffet = new javax.swing.JLabel();
        jlTipoCardapio = new javax.swing.JLabel();
        jlDecoracao = new javax.swing.JLabel();
        jlDanca = new javax.swing.JLabel();
        jlMidia = new javax.swing.JLabel();
        jtxMidia = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jlCodigo = new javax.swing.JLabel();
        jbPesquisar = new javax.swing.JButton();
        jtxBuffet = new javax.swing.JTextField();
        jtxDanca = new javax.swing.JTextField();
        jtxDecoracao2 = new javax.swing.JTextField();
        jtxTipoCardapio = new javax.swing.JTextField();
        jtxMusico = new javax.swing.JTextField();
        jtxGenero = new javax.swing.JTextField();
        jtxResponsavel = new javax.swing.JTextField();
        jtxDescricao = new javax.swing.JTextField();
        jtxIdAtividade = new javax.swing.JTextField();

        jtxDecoracao1.setBorder(null);

        setTitle("Atividade");
        setPreferredSize(new java.awt.Dimension(497, 418));

        JpAtividade.setBackground(new java.awt.Color(146, 183, 203));
        JpAtividade.setForeground(new java.awt.Color(255, 255, 255));

        jlResponsavel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlResponsavel.setForeground(new java.awt.Color(51, 51, 51));
        jlResponsavel.setText("Responsável:");

        jlMusico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlMusico.setForeground(new java.awt.Color(51, 51, 51));
        jlMusico.setText("Músico:");

        jtAtividade.setBackground(new java.awt.Color(145, 164, 181));
        jtAtividade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtAtividade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtAtividade.setForeground(new java.awt.Color(51, 51, 51));
        jtAtividade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idatividade", "descricao", "responsavel", "musico", "genero", "buffet", "tipo_cardapio", "decoracao", "danca", "midia"
            }
        ));
        jtAtividade.setToolTipText("");
        jtAtividade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAtividadeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtAtividade);

        jlDescricao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlDescricao.setForeground(new java.awt.Color(51, 51, 51));
        jlDescricao.setText("Descrição:");

        jlGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlGenero.setForeground(new java.awt.Color(51, 51, 51));
        jlGenero.setText("Gênero:");

        jlBuffet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlBuffet.setForeground(new java.awt.Color(51, 51, 51));
        jlBuffet.setText("Buffet:");

        jlTipoCardapio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlTipoCardapio.setForeground(new java.awt.Color(51, 51, 51));
        jlTipoCardapio.setText("Tipo do Cardápio:");

        jlDecoracao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlDecoracao.setForeground(new java.awt.Color(51, 51, 51));
        jlDecoracao.setText("Decoração:");

        jlDanca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlDanca.setForeground(new java.awt.Color(51, 51, 51));
        jlDanca.setText("Dança:");

        jlMidia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlMidia.setForeground(new java.awt.Color(51, 51, 51));
        jlMidia.setText("Mídia:");

        jtxMidia.setBorder(null);

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jlCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCodigo.setForeground(new java.awt.Color(51, 51, 51));
        jlCodigo.setText("Código:");

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jtxBuffet.setBorder(null);

        jtxDanca.setBorder(null);

        jtxDecoracao2.setBorder(null);

        jtxTipoCardapio.setBorder(null);

        jtxMusico.setBorder(null);

        jtxGenero.setBorder(null);

        jtxResponsavel.setBorder(null);

        jtxDescricao.setBorder(null);

        jtxIdAtividade.setBorder(null);

        javax.swing.GroupLayout JpAtividadeLayout = new javax.swing.GroupLayout(JpAtividade);
        JpAtividade.setLayout(JpAtividadeLayout);
        JpAtividadeLayout.setHorizontalGroup(
            JpAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpAtividadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(JpAtividadeLayout.createSequentialGroup()
                        .addComponent(jlCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxIdAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisar))
                    .addGroup(JpAtividadeLayout.createSequentialGroup()
                        .addComponent(jlDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpAtividadeLayout.createSequentialGroup()
                        .addComponent(jlResponsavel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpAtividadeLayout.createSequentialGroup()
                        .addComponent(jlMusico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxMusico, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpAtividadeLayout.createSequentialGroup()
                        .addComponent(jlDecoracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxDecoracao2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlDanca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxDanca, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpAtividadeLayout.createSequentialGroup()
                        .addComponent(jlMidia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxMidia, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpAtividadeLayout.createSequentialGroup()
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbFechar))
                    .addGroup(JpAtividadeLayout.createSequentialGroup()
                        .addComponent(jlBuffet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxBuffet, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlTipoCardapio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxTipoCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        JpAtividadeLayout.setVerticalGroup(
            JpAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpAtividadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxIdAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCodigo)
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDescricao)
                    .addComponent(jtxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlResponsavel)
                    .addComponent(jtxResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMusico)
                    .addComponent(jtxMusico, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlGenero)
                    .addComponent(jtxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBuffet)
                    .addComponent(jtxBuffet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTipoCardapio)
                    .addComponent(jtxTipoCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDecoracao)
                    .addComponent(jtxDecoracao2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDanca)
                    .addComponent(jtxDanca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMidia)
                    .addComponent(jtxMidia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir)
                    .addComponent(jbFechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Trava eventos do mouse quando clicado em algum objeto do JtAtividade
    private void jtAtividadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAtividadeMouseClicked
        linha = jtAtividade.getSelectedRow();
        if(linha != -1){
            // JTextField
            jtxIdAtividade.setText(jtAtividade.getValueAt(linha, 0) != null ? jtAtividade.getValueAt(linha, 0).toString() : "");
            jtxDescricao.setText(jtAtividade.getValueAt(linha, 1) != null ? jtAtividade.getValueAt(linha, 1).toString() : "");
            jtxResponsavel.setText(jtAtividade.getValueAt(linha, 2) != null ? jtAtividade.getValueAt(linha, 2).toString() : "");
            jtxMusico.setText(jtAtividade.getValueAt(linha, 3) != null ? jtAtividade.getValueAt(linha, 3).toString() : "");
            jtxGenero.setText(jtAtividade.getValueAt(linha, 4) != null ? jtAtividade.getValueAt(linha, 4).toString() : "");
            jtxBuffet.setText(jtAtividade.getValueAt(linha, 5) != null ? jtAtividade.getValueAt(linha, 5).toString() : "");
            jtxTipoCardapio.setText(jtAtividade.getValueAt(linha, 6) != null ? jtAtividade.getValueAt(linha, 6).toString() : "");
            jtxDanca.setText(jtAtividade.getValueAt(linha, 8) != null ? jtAtividade.getValueAt(linha, 8).toString() : "");
            jtxMidia.setText(jtAtividade.getValueAt(linha, 9) != null ? jtAtividade.getValueAt(linha, 9).toString() : "");
            jbNovo.setEnabled(false);
            jbSalvar.setEnabled(false);
            jbEditar.setEnabled(true);
            jbExcluir.setEnabled(true);
            jtxDescricao.setEditable(true);
            jtxResponsavel.setEditable(true);
            jtxMusico.setEditable(true);
            jtxGenero.setEditable(true);
            jtxBuffet.setEditable(true);
            jtxTipoCardapio.setEditable(true);
            jtxBuffet.setEditable(true);
            jtxDanca.setEditable(true);
            jtxMidia.setEditable(true);
            linha = -1;
        }
    }//GEN-LAST:event_jtAtividadeMouseClicked

    // Ações válidas quando pressionado o botão jbNovo
    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jbSalvar.setEnabled(true);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jtxIdAtividade.setEditable(true);
        jtxDescricao.setEditable(true);
        jtxResponsavel.setEditable(true);
        jtxMusico.setEditable(true);
        jtxGenero.setEditable(true);
        jtxBuffet.setEditable(true);
        jtxTipoCardapio.setEditable(true);
        jtxBuffet.setEditable(true);
        jtxDanca.setEditable(true);
        jtxMidia.setEditable(true);
    }//GEN-LAST:event_jbNovoActionPerformed

    // Ações válidas quando pressionado o botão jbSalvar
    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // Strings locais para coletar e armazenar dos JTextField
        String descricao = jtxDescricao.getText();
        String responsavel = jtxResponsavel.getText();
        String musico = jtxMusico.getText();
        String genero = jtxGenero.getText();
        String buffet = jtxBuffet.getText();
        String tipo_cardapio = jtxTipoCardapio.getText();
        String decoracao = jtxBuffet.getText();
        String danca = jtxDanca.getText();
        String midia = jtxMidia.getText();
        if ((jtxDescricao.getText().isEmpty()) || (jtxResponsavel.getText().isEmpty())){
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite descricão e atividade!", "Erro ao salvar atividade", JOptionPane.ERROR_MESSAGE);
        }
        else {
            // Atribuir valores ao AtividadeModel
            AtividadeModel atividade = new AtividadeModel();
            atividade.setDescricao(descricao);
            atividade.setResponsavel(responsavel);
            atividade.setMusico(musico);
            atividade.setGenero(genero);
            atividade.setBuffet(buffet);
            atividade.setTipo_cardapio(tipo_cardapio);
            atividade.setDecoracao(decoracao);
            atividade.setDanca(danca);
            atividade.setMidia(midia);
            // Controller
            AtividadeController controller = new AtividadeController();
            // Comandos condicionais para validar se controller funcionou ou não
            if (controller.inserir(atividade)) {
                JOptionPane.showMessageDialog(this, "Atividade inserida com sucesso!", "Sucesso" ,JOptionPane.INFORMATION_MESSAGE);
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }
            else {
                // Tela alertando o usuário sobre o erro
                JOptionPane.showMessageDialog(this, "Erro ao inserir um atividade!", "Erro" ,JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_jbSalvarActionPerformed

    // Ações válidas quando pressionado o botão jbEditar
    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // Strings e Id locais para coletar e armazenar dos JTextField
        int IdAtividade = Integer.parseInt(jtxIdAtividade.getText());
        String descricao = jtxDescricao.getText();
        String responsavel = jtxResponsavel.getText();
        String musico = jtxMusico.getText();
        String genero = jtxGenero.getText();
        String buffet = jtxBuffet.getText();
        String tipo_cardapio = jtxTipoCardapio.getText();
        String decoracao = jtxBuffet.getText();
        String danca = jtxDanca.getText();
        String midia = jtxMidia.getText();
        // Comandos condicionais para verificar se campo está vazio ou não
        if ((jtxDescricao.getText().isEmpty()) || (jtxResponsavel.getText().isEmpty())){
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite e selecione todos os campos!", "Erro ao salvar atividade", JOptionPane.ERROR_MESSAGE);
        }
        else {
            // Atribuir valores ao AtividadeModel
            AtividadeModel atividade = new AtividadeModel();
            atividade.setIdatividade(IdAtividade);
            atividade.setDescricao(descricao);
            atividade.setResponsavel(responsavel);
            atividade.setMusico(musico);
            atividade.setGenero(genero);
            atividade.setBuffet(buffet);
            atividade.setTipo_cardapio(tipo_cardapio);
            atividade.setDecoracao(decoracao);
            atividade.setDanca(danca);
            atividade.setMidia(midia);
            // Controller
            AtividadeController controller = new AtividadeController();
            // Comandos condicionais para validar se controller funcionou ou não
            if (controller.inserir(atividade)) {
                JOptionPane.showMessageDialog(this, "Local inserido com sucesso!", "Sucesso" ,JOptionPane.INFORMATION_MESSAGE);
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }
            else {
                // Tela alertando o usuário sobre o erro
                JOptionPane.showMessageDialog(this, "Erro ao inserir uma atividade!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_jbEditarActionPerformed

    // Ações quando pressionado o botão jbExcluir
    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // AtividadeModel para excluir o id
        AtividadeModel atividade = new AtividadeModel();
        // Comandos condicionais para verificar se campo está vazio ou não
        if (jtxIdAtividade.getText().isEmpty()) {
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite o código do atividade!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else {
            atividade.setIdatividade(Integer.parseInt(jtxIdAtividade.getText()));
            // Controller
            AtividadeController controller = new AtividadeController();
            // Comandos condicionais para validar se controller funcionou ou não
            if (controller.excluir(atividade)){
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!", "Sucesso" ,JOptionPane.INFORMATION_MESSAGE);
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }
            else {
                // Tela alertando o usuário sobre o erro
                JOptionPane.showMessageDialog(this, "Erro ao excluir atividade!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    // Ação quando pressionado o botão jbFechar
    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        // AtividadeModel para pesquisar por id
        AtividadeModel atividade = new AtividadeModel();
        // Comandos condicionais para verificar se campo está vazio ou não
        if(jtxIdAtividade.getText().isEmpty()){
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Preencha o código da atividade!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else {
            atividade.setIdatividade(Integer.parseInt(jtxIdAtividade.getText()));
            // Controller
            AtividadeController controller = new AtividadeController();
            atividade = controller.selecionar(atividade);
            // Comando condicional para validar se objeto atividade foi encontrado
            if(atividade == null) {
                // Tela alertando que atividade não foi encontrado
                JOptionPane.showMessageDialog(this, "Atividade não encontrada!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            else {
                // Preencher os campos
                jtxDescricao.setText(atividade.getDescricao());
                jtxResponsavel.setText(atividade.getResponsavel());
                jtxMusico.setText(atividade.getMusico());
                jtxGenero.setText(atividade.getGenero());
                jtxBuffet.setText(atividade.getBuffet());
                jtxTipoCardapio.setText(atividade.getTipo_cardapio());
                jtxBuffet.setText(atividade.getDecoracao());
                jtxDanca.setText(atividade.getDanca());
                jtxMidia.setText(atividade.getMidia());
                jbNovo.setEnabled(false);
                jbSalvar.setEnabled(false);
                jbEditar.setEnabled(true);
                jbExcluir.setEnabled(true);  
                jtxIdAtividade.setEditable(false);
                jtxDescricao.setEditable(true);
                jtxResponsavel.setEditable(true);
                jtxMusico.setEditable(true);
                jtxGenero.setEditable(true);
                jtxBuffet.setEditable(true);
                jtxTipoCardapio.setEditable(true);
                jtxBuffet.setEditable(true);
                jtxDanca.setEditable(true);
                jtxMidia.setEditable(true);
            }
        }
    }
        
    // Método para preencher JtAtividade
    private void preencherTabela(){
        AtividadeController controller = new AtividadeController();
        ArrayList<AtividadeModel> lista = controller.selecionarTodos();
        DefaultTableModel modeloTabela = (DefaultTableModel) jtAtividade.getModel();
        modeloTabela.setRowCount(0);
        // Comando condicional para verificar se foi cadastrado
        if (lista.isEmpty()){
            // Tela alertando que nenhuma atividade foi cadastrada
            JOptionPane.showMessageDialog(this, "Nenhuma atividade cadastrada!" ,"Erro", JOptionPane.ERROR_MESSAGE);
        }
        else {
            for(AtividadeModel a: lista) {
                modeloTabela.addRow(new String[]{
                    String.valueOf(a.getIdatividade()),
                    a.getDescricao(),
                    a.getResponsavel(),
                    a.getMusico(),
                    a.getGenero(),
                    a.getBuffet(),
                    a.getTipo_cardapio(),
                    a.getDecoracao(),
                    a.getDanca(),
                    a.getMidia(),
                });
            }
        }
    }
    
    // Método para inicializar os atributos
    private void inicializa(){
        jtxIdAtividade.setEditable(true);
        jtxDescricao.setEditable(false);
        jtxResponsavel.setEditable(false);
        jtxMusico.setEditable(false);
        jtxGenero.setEditable(false);
        jtxBuffet.setEditable(false);
        jtxTipoCardapio.setEditable(false);
        jtxBuffet.setEditable(false);
        jtxDanca.setEditable(false);
        jtxMidia.setEditable(false);
        jbSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbPesquisar.setEnabled(true);
        jbNovo.setEnabled(true);
    }

    // Método para limpar campos
    private void limparCampos(){
        jtxIdAtividade.setText("");
        jtxDescricao.setText("");
        jtxResponsavel.setText("");
        jtxMusico.setText("");
        jtxGenero.setText("");
        jtxBuffet.setText("");
        jtxTipoCardapio.setText("");
        jtxBuffet.setText("");
        jtxDanca.setText("");
        jtxMidia.setText("");
    }//GEN-LAST:event_jbPesquisarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpAtividade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlBuffet;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlDanca;
    private javax.swing.JLabel jlDecoracao;
    private javax.swing.JLabel jlDescricao;
    private javax.swing.JLabel jlGenero;
    private javax.swing.JLabel jlMidia;
    private javax.swing.JLabel jlMusico;
    private javax.swing.JLabel jlResponsavel;
    private javax.swing.JLabel jlTipoCardapio;
    private javax.swing.JTable jtAtividade;
    private javax.swing.JTextField jtxBuffet;
    private javax.swing.JTextField jtxDanca;
    private javax.swing.JTextField jtxDecoracao1;
    private javax.swing.JTextField jtxDecoracao2;
    private javax.swing.JTextField jtxDescricao;
    private javax.swing.JTextField jtxGenero;
    private javax.swing.JTextField jtxIdAtividade;
    private javax.swing.JTextField jtxMidia;
    private javax.swing.JTextField jtxMusico;
    private javax.swing.JTextField jtxResponsavel;
    private javax.swing.JTextField jtxTipoCardapio;
    // End of variables declaration//GEN-END:variables
}
