package view;

// Bibliotecas necessárias
// Model necessários
import model.EventoModel;
import model.AtividadeModel;
import model.LocalModel;
import model.OrganizadorModel;
import model.ProgramacaoModel;
// Controller necessários
import controller.EventoController;
import controller.AtividadeController;
import controller.LocalController;
import controller.OrganizadorController;
import controller.ProgramacaoController;
// Outras bibliotecas
import java.util.ArrayList; 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caior
 */

// EventoView é um JInternalFrame
public class EventoView extends javax.swing.JInternalFrame {
    // Inicializando componentes
    private ArrayList<AtividadeModel> listaAtividades;
    private ArrayList<LocalModel> listaLocais;
    private ArrayList<OrganizadorModel> listaOrganizadores;
    private ArrayList<ProgramacaoModel> listaProgramacoes;
    private int linha = -1; // Atributo contagem para setar valores no JtEvento
    public EventoView() {
        // Métodos
        initComponents();
        preencherTabela();
        inicializa();
        preencheComboAtividade();
        preencheComboLocal();
        preencheComboParticipante();
        preencheComboProgramacao();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jpEvento = new javax.swing.JPanel();
        jlPlano = new javax.swing.JLabel();
        jlValorPlano = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEvento = new javax.swing.JTable();
        jlCategoria = new javax.swing.JLabel();
        jtxValorPlano = new javax.swing.JTextField();
        jtxIdEvento = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jlCodAtividade = new javax.swing.JLabel();
        jlCodLocal = new javax.swing.JLabel();
        jlCodOrganizador = new javax.swing.JLabel();
        jlCodProgramacao = new javax.swing.JLabel();
        jcbPlano = new javax.swing.JComboBox<>();
        jbPesquisar = new javax.swing.JButton();
        jlCodigo = new javax.swing.JLabel();
        jtxCategoria = new javax.swing.JTextField();
        jcbCodAtividade = new javax.swing.JComboBox<>();
        jcbCodLocal = new javax.swing.JComboBox<>();
        jcbCodProgramacao = new javax.swing.JComboBox<>();
        jcbCodParticipante = new javax.swing.JComboBox<>();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setTitle("Evento");
        setPreferredSize(new java.awt.Dimension(497, 418));

        jpEvento.setBackground(new java.awt.Color(235, 141, 141));
        jpEvento.setForeground(new java.awt.Color(255, 255, 255));

        jlPlano.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlPlano.setForeground(new java.awt.Color(255, 255, 255));
        jlPlano.setText("Plano:");

        jlValorPlano.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlValorPlano.setForeground(new java.awt.Color(255, 255, 255));
        jlValorPlano.setText("Valor do Plano:");

        jtEvento.setBackground(new java.awt.Color(203, 120, 120));
        jtEvento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtEvento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtEvento.setForeground(new java.awt.Color(255, 255, 255));
        jtEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "codevento", "categoria", "plano", "valor_plano", "idatividade", "idlocal", "idorganizador", "idprogramacao"
            }
        ));
        jtEvento.setToolTipText("");
        jtEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEventoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtEvento);

        jlCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jlCategoria.setText("Categoria:");

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jlCodAtividade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCodAtividade.setForeground(new java.awt.Color(255, 255, 255));
        jlCodAtividade.setText("Descrição da Atividade:");

        jlCodLocal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCodLocal.setForeground(new java.awt.Color(255, 255, 255));
        jlCodLocal.setText("Nome do Local:");

        jlCodOrganizador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCodOrganizador.setForeground(new java.awt.Color(255, 255, 255));
        jlCodOrganizador.setText("Nome do Organizador:");

        jlCodProgramacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCodProgramacao.setForeground(new java.awt.Color(255, 255, 255));
        jlCodProgramacao.setText("Data do Evento:");

        jcbPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Básico", "Médio", "Completo" }));

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jlCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jlCodigo.setText("Código:");

        javax.swing.GroupLayout jpEventoLayout = new javax.swing.GroupLayout(jpEvento);
        jpEvento.setLayout(jpEventoLayout);
        jpEventoLayout.setHorizontalGroup(
            jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEventoLayout.createSequentialGroup()
                        .addGroup(jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEventoLayout.createSequentialGroup()
                                .addComponent(jlCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxIdEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbPesquisar))
                            .addGroup(jpEventoLayout.createSequentialGroup()
                                .addComponent(jlCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(96, 278, Short.MAX_VALUE))
                    .addGroup(jpEventoLayout.createSequentialGroup()
                        .addGroup(jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                            .addGroup(jpEventoLayout.createSequentialGroup()
                                .addGroup(jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpEventoLayout.createSequentialGroup()
                                        .addComponent(jlPlano)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlValorPlano)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxValorPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpEventoLayout.createSequentialGroup()
                                        .addComponent(jlCodAtividade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbCodAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlCodOrganizador)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbCodParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpEventoLayout.createSequentialGroup()
                                        .addComponent(jlCodLocal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbCodLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlCodProgramacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbCodProgramacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jpEventoLayout.createSequentialGroup()
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbFechar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpEventoLayout.setVerticalGroup(
            jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxIdEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCodigo)
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCategoria)
                    .addComponent(jtxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlValorPlano)
                        .addComponent(jtxValorPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlPlano)
                        .addComponent(jcbPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodAtividade)
                    .addComponent(jcbCodAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCodOrganizador)
                    .addComponent(jcbCodParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodLocal)
                    .addComponent(jcbCodLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCodProgramacao)
                    .addComponent(jcbCodProgramacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir)
                    .addComponent(jbFechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Trava eventos do mouse quando clicado em algum objeto do JtEvento
    private void jtEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEventoMouseClicked
        linha = jtEvento.getSelectedRow();
        if(linha !=-1){
            jtxIdEvento.setText(jtEvento.getValueAt(linha, 0).toString());
            jtxCategoria.setText(jtEvento.getValueAt(linha, 1).toString());
            jtxValorPlano.setText(jtEvento.getValueAt(linha, 4).toString());
            // JComboxbox de Atividade
            String ativ = jtEvento.getValueAt(linha, 3).toString();
            jcbCodAtividade.setSelectedItem(ativ);
            // JComboxbox de Local
            String loca = jtEvento.getValueAt(linha, 4).toString();
            jcbCodLocal.setSelectedItem(loca);
            // JComboxbox de Participante
            String part = jtEvento.getValueAt(linha, 5).toString();
            jcbCodParticipante.setSelectedItem(part);
            // JComboxbox de Programação
            String prog = jtEvento.getValueAt(linha, 6).toString();
            jcbCodProgramacao.setSelectedItem(prog);
            // JComboBox de Plano
            jbNovo.setEnabled(false);
            jbSalvar.setEnabled(false);
            jbEditar.setEnabled(true);
            jbExcluir.setEnabled(true);
            jtxIdEvento.setEditable(false);
            jtxCategoria.setEditable(true);
            jtxValorPlano.setEditable(true);  
            jcbPlano.setEditable(true);
            linha = -1;
        }
    }//GEN-LAST:event_jtEventoMouseClicked

    // Ações válidas quando pressionado o botão jbNovo
    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jbPesquisar.setEnabled(false);
        jbNovo.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbSalvar.setEnabled(true);
        jtxIdEvento.setEditable(false);
        jtxCategoria.setEditable(true);
        jtxValorPlano.setEditable(true);
    }//GEN-LAST:event_jbNovoActionPerformed

    // Ações válidas quando pressionado o botão jbSalvar
    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // Comandos condicionais para verificar se campo está vazio ou não
        if((jtxCategoria.getText().isEmpty()) || (jtxValorPlano.getText()).isEmpty() || (jcbPlano.getSelectedItem() == null)) {
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            // Inteiros, Strings e Objetos locais para coletar e armazenar dos JTextField e JComboBox
            // Strings
            String categoria = jtxCategoria.getText();
            String ativ = (String) jcbCodAtividade.getSelectedItem();
            String loca = (String) jcbCodLocal.getSelectedItem();
            String part = (String) jcbCodParticipante.getSelectedItem();
            String prog = (String) jcbCodProgramacao.getSelectedItem();
            // Objeto
            Object plano = (Object) jcbPlano.getSelectedItem();
            // Inteiros
            int valor_plano = Integer.parseInt(jtxValorPlano.getText());
            // Comandos de repetição para coletar a lista
            int atividade = 0;
            for(int i=0; i<listaAtividades.size();i++){
                if(ativ.equals(listaAtividades.get(i).getDescricao())){
                    atividade = listaAtividades.get(i).getIdatividade();
                    break;
                }
            }
            // Local
            int local = 0;
            for(int i=0; i<listaLocais.size();i++){
                if(loca.equals(listaLocais.get(i).getNome())){
                    local = listaLocais.get(i).getIdlocal();
                    break;
                }
            }
            // Participante
            int organizador = 0;
            for(int i=0; i<listaOrganizadores.size();i++){
                if(part.equals(listaOrganizadores.get(i).getNome())){
                    organizador = listaOrganizadores.get(i).getIdorganizador();
                    break;
                }
            }
            // Programação
            int programacao = 0;
            for(int i=0; i<listaProgramacoes.size();i++){
                if(prog.equals(listaProgramacoes.get(i).getData_evento())){
                    programacao = listaProgramacoes.get(i).getIdprogramacao();
                    break;
                }
            }
            EventoModel evento = new EventoModel();
            evento.setCategoria(categoria);
            evento.setValor_plano(valor_plano);
            evento.setPlano(plano.toString());
            // Chaves Estrangeiras
            evento.getAtividade().setIdatividade(atividade);
            evento.getLocal().setIdlocal(local);
            evento.getOrganizador().setIdorganizador(organizador);
            evento.getProgramacao().setIdprogramacao(programacao);
            //CONTROLLER
            EventoController controller = new EventoController();
            // Comandos condicionais para validar se controller funcionou ou não
            if(controller.inserir(evento)){
                JOptionPane.showMessageDialog(this, "Evento inserido com sucesso!", "Sucesso" ,JOptionPane.INFORMATION_MESSAGE);
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }else
                JOptionPane.showMessageDialog(this, "Erro ao inserir o evento!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    // Ações válidas quando pressionado o botão jbEditar
    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // Comandos condicionais para verificar se campo está vazio ou não
        if((jtxCategoria.getText().isEmpty()) || (jtxValorPlano.getText()).isEmpty() || (jcbPlano.getSelectedItem() == null)){
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite e selecione todos os campos!", "Erro ao salvar evento", JOptionPane.ERROR_MESSAGE);
        }
        else{
            // Atribuir valores ao EventoModel
            // Inteiros, Strings e Objetos locais para coletar e armazenar dos JTextField e JComboBox
            // Strings
            String categoria = jtxCategoria.getText();
            String ativ = (String) jcbCodAtividade.getSelectedItem();
            String loca = (String) jcbCodLocal.getSelectedItem();
            String part = (String) jcbCodParticipante.getSelectedItem();
            String prog = (String) jcbCodProgramacao.getSelectedItem();
            // Objeto
            Object plano = (Object) jcbPlano.getSelectedItem();
            // Inteiros
            int valor_plano = Integer.parseInt(jtxValorPlano.getText());
            // Comandos de repetição para coletar a lista
            // Atividade
            int atividade = 0;
            for(int i=0; i<listaAtividades.size();i++){
                if(ativ.equals(listaAtividades.get(i).getDescricao())){
                    atividade = listaAtividades.get(i).getIdatividade();
                    break;
                }
            }
            // Local
            int local = 0;
            for(int i=0; i<listaLocais.size();i++){
                if(loca.equals(listaLocais.get(i).getNome())){
                    local = listaLocais.get(i).getIdlocal();
                    break;
                }
            }
            // Participante
            int organizador = 0;
            for(int i=0; i<listaOrganizadores.size();i++){
                if(part.equals(listaOrganizadores.get(i).getNome())){
                    organizador = listaOrganizadores.get(i).getIdorganizador();
                    break;
                }
            }
            // Programação
            int programacao = 0;
            for(int i=0; i<listaProgramacoes.size();i++){
                if(prog.equals(listaProgramacoes.get(i).getData_evento())){
                    programacao = listaProgramacoes.get(i).getIdprogramacao();
                    break;
                }
            }
            EventoModel evento = new EventoModel();
            evento.setCategoria(categoria);
            evento.setValor_plano(valor_plano);
            evento.setPlano(plano.toString());
            // Chaves Estrangeiras
            evento.getAtividade().setIdatividade(atividade);
            evento.getLocal().setIdlocal(local);
            evento.getOrganizador().setIdorganizador(organizador);
            evento.getProgramacao().setIdprogramacao(programacao);
            //CONTROLLER
            EventoController controller = new EventoController();
            // Comandos condicionais para validar se controller funcionou ou não
            if(controller.inserir(evento)){
                JOptionPane.showMessageDialog(this, "Evento editado com sucesso!", "Sucesso" , JOptionPane.INFORMATION_MESSAGE);
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }else
                JOptionPane.showMessageDialog(this, "Erro ao editar o evento!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    // Ações válidas quando pressionado o botão jbEditar
    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // EventoModel para excluir o id
        EventoModel evento = new EventoModel();
        // Comandos condicionais para verificar se campo está vazio ou não
        if(jtxIdEvento.getText().isEmpty()) {
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite o código do evento!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            evento.setCodevento(Integer.parseInt(jtxIdEvento.getText()));
            // Controller 
            EventoController controller = new EventoController();
            // Comandos condicionais para validar se controller funcionou ou não
            if(controller.excluir(evento)){
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
                limparCampos();
                inicializa();
                preencherTabela();
            }else 
                // Tela alertando o usuário sobre o erro
                JOptionPane.showMessageDialog(this, "Erro ao Excluir!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    // Ação quando pressionado o botão jbFechar
    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        // EventoModel para pesquisar por id
        EventoModel evento = new EventoModel();
        // Comandos condicionais para verificar se campo está vazio ou não
        if(jtxIdEvento.getText().isEmpty()){
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Preencha o código do evento!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else {
            evento.setCodevento(Integer.parseInt(jtxIdEvento.getText()));
            // Controller
            EventoController controller = new EventoController();
            evento = controller.selecionar(evento);
            // Comando condicional para validar se objeto evento foi encontrado
            if(evento == null) {
                // Tela alertando que evento não foi encontrado
                JOptionPane.showMessageDialog(this, "Evento não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            else {
                // Preencher os campos
                jtxCategoria.setText(evento.getCategoria());
                jcbPlano.setSelectedItem(evento.getPlano());
                jtxValorPlano.setText(String.valueOf(evento.getValor_plano()));
                jcbCodAtividade.setSelectedItem(evento.getAtividade().getDescricao());
                jcbCodLocal.setSelectedItem(evento.getLocal().getNome());
                jcbCodParticipante.setSelectedItem(evento.getOrganizador());
                jcbCodProgramacao.setSelectedItem(evento.getProgramacao());
                jbNovo.setEnabled(false);
                jbSalvar.setEnabled(false);
                jbEditar.setEnabled(true);
                jbExcluir.setEnabled(true);
                jtxIdEvento.setEditable(false);
                jtxCategoria.setEditable(true);
                jcbPlano.setEditable(true);
                jtxValorPlano.setEditable(true);
                jcbCodAtividade.setEditable(true);
                jcbCodLocal.setEditable(true);
                jcbCodParticipante.setEditable(true);
                jcbCodProgramacao.setEditable(true);
            }
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed
    
    // Método para preencher JtEvento
    private void preencherTabela(){
        EventoController controller = new EventoController();
        ArrayList<EventoModel> lista = controller.selecionarTodos();
        DefaultTableModel modeloTabela = (DefaultTableModel) jtEvento.getModel();
        modeloTabela.setRowCount(0);
        // Comando condicional para verificar se foi cadastrado
        if (lista.isEmpty()){
            // Tela alertando que nenhum evento foi cadastrado
            JOptionPane.showMessageDialog(this, "Nenhum evento cadastrado!" ,"Erro", JOptionPane.ERROR_MESSAGE);
        }
        else {
            for(EventoModel e: lista) {
                modeloTabela.addRow(new String[]{
                    String.valueOf(e.getCodevento()),
                    e.getCategoria(),
                    e.getPlano(),
                    String.valueOf(e.getValor_plano()),
                    e.getAtividade().getDescricao(),
                    e.getLocal().getNome(),
                    e.getOrganizador().getNome(),
                    e.getProgramacao().getData_evento()
                });
            }
        }
    }
    
    // Método para inicializar os atributos
    private void inicializa(){
        jtxIdEvento.setEditable(true);
        jtxCategoria.setEditable(false);
        jtxValorPlano.setEditable(false);
        jbSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbPesquisar.setEnabled(true);
        jbNovo.setEnabled(true);
    }
    
    // Método para limpar campos
    private void limparCampos(){
        jtxIdEvento.setText("");
        jtxCategoria.setText("");
        jtxValorPlano.setText("");
        jcbPlano.setSelectedIndex(0);
        jcbCodAtividade.setSelectedIndex(0);
        jcbCodLocal.setSelectedIndex(0);
        jcbCodParticipante.setSelectedIndex(0);
        jcbCodProgramacao.setSelectedIndex(0);
    } 
    
    // PrencherComboBox dos id das chaves estrangeiras
    // ComboBoxAtividade
    private void preencheComboAtividade(){
        AtividadeController controller = new AtividadeController();
        listaAtividades = new ArrayList<>();
        listaAtividades = controller.selecionarTodos();
        if(!listaAtividades.isEmpty()){
            for(AtividadeModel a: listaAtividades)
                jcbCodAtividade.addItem(a.getDescricao());
        }
        }
    // ComboBoxLocal
    private void preencheComboLocal(){
        LocalController controller = new LocalController();
        listaLocais = new ArrayList<>();
        listaLocais = controller.selecionarTodos();
        if(!listaLocais.isEmpty()){
            for(LocalModel a: listaLocais)
                jcbCodLocal.addItem(a.getNome());
        }
    }
    // ComboBoxParticipante
    private void preencheComboParticipante() {
        OrganizadorController controller = new OrganizadorController();
        listaOrganizadores = new ArrayList<>();
        listaOrganizadores = controller.selecionarTodos();
        if(!listaOrganizadores.isEmpty()){
            for(OrganizadorModel o: listaOrganizadores)
                jcbCodParticipante.addItem(o.getNome());
        }
    }
    // ComboBoxProgramação
    private void preencheComboProgramacao(){
        ProgramacaoController controller = new ProgramacaoController();
        listaProgramacoes = new ArrayList<>();
        listaProgramacoes = controller.selecionarTodos();
        if(!listaProgramacoes.isEmpty()){
            for(ProgramacaoModel p: listaProgramacoes)
                jcbCodProgramacao.addItem(p.getData_evento());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcbCodAtividade;
    private javax.swing.JComboBox<String> jcbCodLocal;
    private javax.swing.JComboBox<String> jcbCodParticipante;
    private javax.swing.JComboBox<String> jcbCodProgramacao;
    private javax.swing.JComboBox<String> jcbPlano;
    private javax.swing.JLabel jlCategoria;
    private javax.swing.JLabel jlCodAtividade;
    private javax.swing.JLabel jlCodLocal;
    private javax.swing.JLabel jlCodOrganizador;
    private javax.swing.JLabel jlCodProgramacao;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlPlano;
    private javax.swing.JLabel jlValorPlano;
    private javax.swing.JPanel jpEvento;
    private javax.swing.JTable jtEvento;
    private javax.swing.JTextField jtxCategoria;
    private javax.swing.JTextField jtxIdEvento;
    private javax.swing.JTextField jtxValorPlano;
    // End of variables declaration//GEN-END:variables
}

