package view;

// Bibliotecas necessárias
import model.LocalModel; // Model
import controller.LocalController; // Controller
import java.awt.Dimension;
import java.util.ArrayList; 
import java.util.List;
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caior
 */

// LocalView é um JInternalFrame
public class LocalView extends javax.swing.JInternalFrame {
    
    // Inicializando componentes
    private int linha = -1; // Atributo contagem para setar valores no JtTable
    public LocalView() {
        // Métodos
        initComponents();
        // Barras de rolagem do JScrollPane
        jspAcessibilidade.getVerticalScrollBar().setPreferredSize(new Dimension(0, Integer.MAX_VALUE));
        jspRecursosDisponiveis.getVerticalScrollBar().setPreferredSize(new Dimension(0, Integer.MAX_VALUE));
        jspAcessibilidade.getHorizontalScrollBar().setPreferredSize(new Dimension(Integer.MAX_VALUE,12));
        jspRecursosDisponiveis.getHorizontalScrollBar().setPreferredSize(new Dimension(Integer.MAX_VALUE,12));
        preencherTabela();
        inicializa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpLocal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLocal = new javax.swing.JTable();
        jlCpf = new javax.swing.JLabel();
        jlEndereco = new javax.swing.JLabel();
        jlCapacidade = new javax.swing.JLabel();
        jlRecursosDisponiveis = new javax.swing.JLabel();
        jlAcessibilidade = new javax.swing.JLabel();
        jtxNome = new javax.swing.JTextField();
        jtxEndereco = new javax.swing.JTextField();
        jtxCapacidade = new javax.swing.JTextField();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jlCodigo = new javax.swing.JLabel();
        jtxIdLocal = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlstRecursosDisponiveis = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlstAcessibilidade = new javax.swing.JList<>();
        jspRecursosDisponiveis = new javax.swing.JScrollPane();
        jtaRecursosDisponiveis = new javax.swing.JTextArea();
        jspAcessibilidade = new javax.swing.JScrollPane();
        jtaAcessibilidade = new javax.swing.JTextArea();
        jlQuantidadeParticipantes = new javax.swing.JLabel();
        jtxQuantidadeParticipantes = new javax.swing.JTextField();

        setTitle("Local");
        setPreferredSize(new java.awt.Dimension(497, 418));

        jpLocal.setBackground(new java.awt.Color(180, 224, 165));
        jpLocal.setForeground(new java.awt.Color(255, 255, 255));

        jtLocal.setBackground(new java.awt.Color(139, 200, 139));
        jtLocal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtLocal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtLocal.setForeground(new java.awt.Color(51, 51, 51));
        jtLocal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idlocal", "nome", "endereço", "capacidade", "recursos disponíveis", "acessibilidade", "quantidade_participantes"
            }
        ));
        jtLocal.setToolTipText("");
        jtLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLocalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtLocal);

        jlCpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCpf.setForeground(new java.awt.Color(255, 255, 255));
        jlCpf.setText("Nome:");

        jlEndereco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlEndereco.setForeground(new java.awt.Color(255, 255, 255));
        jlEndereco.setText("Endereço:");

        jlCapacidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCapacidade.setForeground(new java.awt.Color(255, 255, 255));
        jlCapacidade.setText("Capacidade:");

        jlRecursosDisponiveis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlRecursosDisponiveis.setForeground(new java.awt.Color(255, 255, 255));
        jlRecursosDisponiveis.setText("Recursos Disponíveis:");

        jlAcessibilidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlAcessibilidade.setForeground(new java.awt.Color(255, 255, 255));
        jlAcessibilidade.setText("Acessibilidade:");

        jtxNome.setBorder(null);

        jtxEndereco.setBorder(null);

        jtxCapacidade.setBorder(null);

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jlCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jlCodigo.setText("Código:");

        jtxIdLocal.setBorder(null);

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jlstRecursosDisponiveis.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Projetor multimídia", "Sistema de som", "Estrutura para apresentações", "Banheiros químicos", "Tela para projeção", "Mesas e cadeiras", "Microfone sem fio", "Máquina de fumaça", "Equipamento para DJ", "Gerador de energia", "Equipamento de audiovisual" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlstRecursosDisponiveis);

        jlstAcessibilidade.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Rampas de acesso para cadeirantes", "Banheiros adaptados", "Elevadores ou plataformas elevatórias", "Assentos reservados para PCD", "Atendimento prioritário", "Vaga reservada para PCD", "Plataformas com corrimão", "Legenda em tempo real" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlstAcessibilidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(jlstAcessibilidade);

        jtaRecursosDisponiveis.setColumns(20);
        jtaRecursosDisponiveis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtaRecursosDisponiveis.setRows(5);
        jspRecursosDisponiveis.setViewportView(jtaRecursosDisponiveis);

        jtaAcessibilidade.setColumns(20);
        jtaAcessibilidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtaAcessibilidade.setRows(5);
        jspAcessibilidade.setViewportView(jtaAcessibilidade);

        jlQuantidadeParticipantes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlQuantidadeParticipantes.setForeground(new java.awt.Color(255, 255, 255));
        jlQuantidadeParticipantes.setText("Quantidade de Participantes:");

        jtxQuantidadeParticipantes.setBorder(null);

        javax.swing.GroupLayout jpLocalLayout = new javax.swing.GroupLayout(jpLocal);
        jpLocal.setLayout(jpLocalLayout);
        jpLocalLayout.setHorizontalGroup(
            jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLocalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLocalLayout.createSequentialGroup()
                        .addGroup(jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpLocalLayout.createSequentialGroup()
                                .addComponent(jlRecursosDisponiveis)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jspRecursosDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(12, 12, 12)
                        .addGroup(jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlAcessibilidade)
                            .addComponent(jScrollPane3)
                            .addComponent(jspAcessibilidade, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(jpLocalLayout.createSequentialGroup()
                        .addGroup(jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpLocalLayout.createSequentialGroup()
                                .addComponent(jlCapacidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlQuantidadeParticipantes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxQuantidadeParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpLocalLayout.createSequentialGroup()
                                .addComponent(jlCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxIdLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPesquisar))
                            .addGroup(jpLocalLayout.createSequentialGroup()
                                .addComponent(jlCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(jpLocalLayout.createSequentialGroup()
                        .addGroup(jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                            .addGroup(jpLocalLayout.createSequentialGroup()
                                .addComponent(jlEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxEndereco)))
                        .addContainerGap())
                    .addGroup(jpLocalLayout.createSequentialGroup()
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbFechar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpLocalLayout.setVerticalGroup(
            jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLocalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPesquisar)
                    .addComponent(jtxIdLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCodigo))
                .addGap(9, 9, 9)
                .addGroup(jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEndereco)
                    .addComponent(jtxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCapacidade)
                    .addComponent(jtxCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQuantidadeParticipantes)
                    .addComponent(jtxQuantidadeParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRecursosDisponiveis)
                    .addComponent(jlAcessibilidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspAcessibilidade, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jspRecursosDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir)
                    .addComponent(jbFechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpLocal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 571, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Trava eventos do mouse quando clicado em algum objeto do JtLocal
    private void jtLocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLocalMouseClicked
        linha = jtLocal.getSelectedRow();
        if(linha != -1){
            // JTextField
            jtxIdLocal.setText(jtLocal.getValueAt(linha,0).toString());
            jtxNome.setText(jtLocal.getValueAt(linha, 1).toString());
            jtxEndereco.setText(jtLocal.getValueAt(linha, 2).toString());
            jtxCapacidade.setText(jtLocal.getValueAt(linha, 3).toString());
            // JList, irá mostrar objetos selecionadas no jlist
            String recursos_texto = jtLocal.getValueAt(linha, 4).toString();
            String acessibilidade_texto = jtLocal.getValueAt(linha, 5).toString();
            jtxQuantidadeParticipantes.setText(jtLocal.getValueAt(linha, 6).toString());
            jtaRecursosDisponiveis.setText(recursos_texto);
            jtaAcessibilidade.setText(acessibilidade_texto);
            // Botões
            jbNovo.setEnabled(false);
            jbSalvar.setEnabled(false);
            jbEditar.setEnabled(true);
            jbExcluir.setEnabled(true);
            jtxIdLocal.setEditable(false);
            jtxNome.setEditable(true);
            jtxCapacidade.setEditable(true);
            jtxEndereco.setEditable(true);
            jtxQuantidadeParticipantes.setEditable(true);
            jlstRecursosDisponiveis.setEnabled(true);
            jlstAcessibilidade.setEnabled(true);
            jtaRecursosDisponiveis.setEnabled(true);
            jtaAcessibilidade.setEnabled(true);
            linha = -1;
    }//GEN-LAST:event_jtLocalMouseClicked
    }
    
    // Ações válidas quando pressionado o botão jbNovo
    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbSalvar.setEnabled(true);
        jtxIdLocal.setEditable(true);
        jtxEndereco.setEditable(true);
        jtxCapacidade.setEditable(true);
        jtxQuantidadeParticipantes.setEditable(true);
        jlstRecursosDisponiveis.setEnabled(true);
        jlstAcessibilidade.setEnabled(true);
        jtaRecursosDisponiveis.setEditable(false);
        jtaAcessibilidade.setEditable(false);
    }//GEN-LAST:event_jbNovoActionPerformed

    // Ações válidas quando pressionado o botão jbSalvar
    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // Inteiros, Strings e Listas locais para coletar e armazenar dos JTextField e JComboBox
        String nome = jtxNome.getText();
        String endereco = jtxEndereco.getText();
        int quantidade_participantes = Integer.parseInt(jtxQuantidadeParticipantes.getText());
        int capacidade = Integer.parseInt(jtxCapacidade.getText());
        List <String> recursos_selecionados = jlstRecursosDisponiveis.getSelectedValuesList();
        List <String> acessibilidades_selecionadas = jlstAcessibilidade.getSelectedValuesList();
        // Comandos condicionais para verificar se campo está vazio ou não
        if ((jtxNome.getText().isEmpty()) || (jtxEndereco.getText().isEmpty()) || (jtxCapacidade.getText().isEmpty()) || (recursos_selecionados.isEmpty()) || (acessibilidades_selecionadas.isEmpty()) || (jtxQuantidadeParticipantes.getText().isEmpty())){
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite e selecione todos os campos!", "Erro ao salvar local", JOptionPane.ERROR_MESSAGE);
        }
        else {
            // Atribuir valores ao LocalModel
            LocalModel local = new LocalModel();
            // JTextField
            local.setNome(nome);
            local.setEndereco(endereco);
            local.setCapacidade(capacidade);
            local.setQuantidade_participantes(quantidade_participantes);
            // Jlist
            String recursos_texto = String.join(", ", recursos_selecionados);
            local.setRecursos_disponiveis(recursos_texto);          
            String acessibilidade_texto = String.join(", ", acessibilidades_selecionadas);
            local.setAcessibilidade(acessibilidade_texto);
            // Controller
            LocalController controller = new LocalController();
            // Comandos condicionais para validar se controller funcionou ou não
            if (controller.inserir(local)) {
                JOptionPane.showMessageDialog(this, "Local inserido com sucesso!", "Sucesso" ,JOptionPane.INFORMATION_MESSAGE);
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }
            else {
                // Tela alertando o usuário sobre o erro
                JOptionPane.showMessageDialog(this, "Erro ao inserir um local!", "Erro" ,JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    // Ações válidas quando pressionado o botão jbEditar
    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // Inteiros, Strings e Objetos locais para coletar e armazenar dos JTextField e JComboBox
        int Idlocal = Integer.parseInt(jtxIdLocal.getText());
        int capacidade = Integer.parseInt(jtxCapacidade.getText());
        int quantidade_participantes = Integer.parseInt(jtxQuantidadeParticipantes.getText());
        String nome = jtxNome.getText();
        String endereco = jtxEndereco.getText();
        List <String> recursos_selecionados = jlstRecursosDisponiveis.getSelectedValuesList();
        List <String> acessibilidades_selecionadas = jlstAcessibilidade.getSelectedValuesList();
        // Comandos condicionais para verificar se campo está vazio ou não
        if ((jtxNome.getText().isEmpty()) || (jtxEndereco.getText().isEmpty()) || (jtxCapacidade.getText().isEmpty()) || (recursos_selecionados.isEmpty()) || (acessibilidades_selecionadas.isEmpty()) || (jtxQuantidadeParticipantes.getText().isEmpty())){
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite e selecione todos os campos!", "Erro ao salvar local", JOptionPane.ERROR_MESSAGE);
        }
        else {
            // Atribuir valores ao LocalModel
            LocalModel local = new LocalModel();
            // Int idlocal
            local.setIdlocal(Idlocal);
            // JTextField
            local.setNome(nome);
            local.setEndereco(endereco);
            local.setCapacidade(capacidade);
            local.setQuantidade_participantes(quantidade_participantes);
            // JList
            String recursos_texto = String.join(", ", recursos_selecionados);
            local.setRecursos_disponiveis(recursos_texto);          
            String acessibilidade_texto = String.join(", ", acessibilidades_selecionadas);
            local.setAcessibilidade(acessibilidade_texto);                          
            // Controller
            LocalController controller = new LocalController();
            // Comandos condicionais para validar se controller funcionou ou não
            if (controller.inserir(local)) {
                JOptionPane.showMessageDialog(this, "Local inserido com sucesso!", "Sucesso" ,JOptionPane.INFORMATION_MESSAGE);
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }
            else {
                // Tela alertando o usuário sobre o erro
                JOptionPane.showMessageDialog(this, "Erro ao inserir um local!", "Erro", JOptionPane.ERROR_MESSAGE);
            }    
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    // Ações quando pressionado o botão jbExcluir
    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // LocalModel para excluir o id
        LocalModel local = new LocalModel();
        // Comandos condicionais para verificar se campo está vazio ou não
        if (jtxIdLocal.getText().isEmpty()) {
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite o código do local!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else {
            local.setIdlocal(Integer.parseInt(jtxIdLocal.getText()));
            // Controller
            LocalController controller = new LocalController();
            // Comandos condicionais para validar se controller funcionou ou não
            if (controller.excluir(local)){
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!", "Sucesso" ,JOptionPane.INFORMATION_MESSAGE);
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }
            else {
                // Tela alertando o usuário sobre o erro
                JOptionPane.showMessageDialog(this, "Erro ao excluir local!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    // Ação quando pressionado o botão jbFechar
    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    // Ações quando pressionado o botão jbPesquisar
    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        // LocalModel para pesquisar por id
        LocalModel local = new LocalModel();
        // Comandos condicionais para verificar se campo está vazio ou não
        if(jtxIdLocal.getText().isEmpty()){
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Preencha o código do local!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else {
            local.setIdlocal(Integer.parseInt(jtxIdLocal.getText()));
            // Controller
            LocalController controller = new LocalController();
            local = controller.selecionar(local);
            // Comando condicional para validar se objeto local foi encontrado
            if(local == null) {
                // Tela alertando que local não foi encontrado
                JOptionPane.showMessageDialog(this, "Local não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            else {
                // Preencher os campos
                jtxNome.setText(local.getNome());
                jtxEndereco.setText(local.getEndereco());
                jtxCapacidade.setText(String.valueOf(local.getCapacidade()));
                jtxQuantidadeParticipantes.setText(String.valueOf(local.getQuantidade_participantes()));
                jbNovo.setEnabled(false);
                jbSalvar.setEnabled(false);
                jbEditar.setEnabled(true);
                jbExcluir.setEnabled(true);
                jtxIdLocal.setEditable(false);
                jtxEndereco.setEditable(true);
                jtxNome.setEditable(true);
                jtxCapacidade.setEditable(true);
                jtxQuantidadeParticipantes.setEditable(true);
                jlstRecursosDisponiveis.setEnabled(true);
                jlstAcessibilidade.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    // Método para preencher JtLocal
    private void preencherTabela(){
        LocalController controller = new LocalController();
        ArrayList<LocalModel> lista = controller.selecionarTodos();
        DefaultTableModel modeloTabela = (DefaultTableModel) jtLocal.getModel();
        modeloTabela.setRowCount(0);
        // Comando condicional para verificar se foi cadastrado
        if (lista.isEmpty()){
            // Tela alertando que nenhum local foi cadastrado
            JOptionPane.showMessageDialog(this, "Nenhum local cadastrado!" ,"Erro", JOptionPane.ERROR_MESSAGE);
        }
        else {
            for(LocalModel l: lista) {
                modeloTabela.addRow(new String[]{
                    String.valueOf(l.getIdlocal()),
                    l.getNome(),
                    l.getEndereco(),
                    String.valueOf(l.getCapacidade()),
                    l.getRecursos_disponiveis(),
                    l.getAcessibilidade(),
                    String.valueOf(l.getQuantidade_participantes())
                });
            }
        }
    }
    
    // Método para inicializar os atributos
    private void inicializa(){
        jtxIdLocal.setEditable(true);
        jtxEndereco.setEditable(false);
        jtxCapacidade.setEditable(false);
        jtxQuantidadeParticipantes.setEditable(false);
        jlstRecursosDisponiveis.setEnabled(false);
        jlstAcessibilidade.setEnabled(false);
        jbSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbPesquisar.setEnabled(true);
        jbNovo.setEnabled(true);
    }
    
    // Método para limpar campos
    private void limparCampos(){
        jtxIdLocal.setText("");
        jtxNome.setText("");
        jtxEndereco.setText("");
        jtxCapacidade.setText("");
        jtxQuantidadeParticipantes.setText("");
        jlstRecursosDisponiveis.setSelectedIndex(0);
        jlstAcessibilidade.setSelectedIndex(0);
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlAcessibilidade;
    private javax.swing.JLabel jlCapacidade;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlQuantidadeParticipantes;
    private javax.swing.JLabel jlRecursosDisponiveis;
    private javax.swing.JList<String> jlstAcessibilidade;
    private javax.swing.JList<String> jlstRecursosDisponiveis;
    private javax.swing.JPanel jpLocal;
    private javax.swing.JScrollPane jspAcessibilidade;
    private javax.swing.JScrollPane jspRecursosDisponiveis;
    private javax.swing.JTable jtLocal;
    private javax.swing.JTextArea jtaAcessibilidade;
    private javax.swing.JTextArea jtaRecursosDisponiveis;
    private javax.swing.JTextField jtxCapacidade;
    private javax.swing.JTextField jtxEndereco;
    private javax.swing.JTextField jtxIdLocal;
    private javax.swing.JTextField jtxNome;
    private javax.swing.JTextField jtxQuantidadeParticipantes;
    // End of variables declaration//GEN-END:variables
}
