package view;

// Bibliotecas necessárias
import model.OrganizadorModel; // Model
import controller.OrganizadorController; // Controller
import java.util.ArrayList; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caior
 */

// OrganizadorView é um JInternalFrame
public class OrganizadorView extends javax.swing.JInternalFrame {
    
    // Inicializando componentes
    private int linha = -1; // Atributo contagem para setar valores no JtOrganizador
    public OrganizadorView() {
        // Métodos
        initComponents();
        preencherTabela();
        inicializa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpOrganizador = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jlDataNasc = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jtxDataNasc = new javax.swing.JTextField();
        jtxNome = new javax.swing.JTextField();
        jtxCpf = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jtxTelefone = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jlCodigo = new javax.swing.JLabel();
        jtxIdOrganizador = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtOrganizador = new javax.swing.JTable();

        setTitle("Organizador");
        setPreferredSize(new java.awt.Dimension(497, 418));

        jpOrganizador.setBackground(new java.awt.Color(232, 235, 177));
        jpOrganizador.setForeground(new java.awt.Color(255, 255, 255));

        jlNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlNome.setForeground(new java.awt.Color(114, 90, 43));
        jlNome.setText("Nome:");

        jlDataNasc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlDataNasc.setForeground(new java.awt.Color(114, 90, 43));
        jlDataNasc.setText("Data de Nascimento:");

        jlCpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCpf.setForeground(new java.awt.Color(114, 90, 43));
        jlCpf.setText("Cpf:");

        jlTelefone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlTelefone.setForeground(new java.awt.Color(114, 90, 43));
        jlTelefone.setText("Telefone:");

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jlCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCodigo.setForeground(new java.awt.Color(114, 90, 43));
        jlCodigo.setText("Código:");

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jtOrganizador.setBackground(new java.awt.Color(211, 210, 162));
        jtOrganizador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtOrganizador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtOrganizador.setForeground(new java.awt.Color(51, 51, 51));
        jtOrganizador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idorganizador", "nome", "cpf", "data_nasc", "telefone"
            }
        ));
        jtOrganizador.setToolTipText("");
        jtOrganizador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtOrganizadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtOrganizador);

        javax.swing.GroupLayout jpOrganizadorLayout = new javax.swing.GroupLayout(jpOrganizador);
        jpOrganizador.setLayout(jpOrganizadorLayout);
        jpOrganizadorLayout.setHorizontalGroup(
            jpOrganizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOrganizadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOrganizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpOrganizadorLayout.createSequentialGroup()
                        .addGroup(jpOrganizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpOrganizadorLayout.createSequentialGroup()
                                .addGroup(jpOrganizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpOrganizadorLayout.createSequentialGroup()
                                        .addComponent(jlCodigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxIdOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbPesquisar))
                                    .addGroup(jpOrganizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpOrganizadorLayout.createSequentialGroup()
                                            .addComponent(jlTelefone)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtxTelefone))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpOrganizadorLayout.createSequentialGroup()
                                            .addComponent(jlDataNasc)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtxDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpOrganizadorLayout.createSequentialGroup()
                                .addComponent(jlNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jpOrganizadorLayout.createSequentialGroup()
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbFechar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpOrganizadorLayout.setVerticalGroup(
            jpOrganizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOrganizadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOrganizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo)
                    .addComponent(jtxIdOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOrganizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpf)
                    .addComponent(jtxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOrganizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDataNasc)
                    .addComponent(jtxDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOrganizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefone)
                    .addComponent(jtxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jpOrganizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir)
                    .addComponent(jbFechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpOrganizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpOrganizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Ações válidas quando pressionado o botão jbNovo
    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jbEditar.setEnabled(false);
        jtxNome.setEditable(true);
        jbExcluir.setEnabled(false);
        jbSalvar.setEnabled(true);
        jtxIdOrganizador.setEditable(true);
        jtxCpf.setEditable(true);
        jtxDataNasc.setEditable(true);
        jtxTelefone.setEditable(true);
    }//GEN-LAST:event_jbNovoActionPerformed

    // Ações válidas quando pressionado o botão jbSalvar
    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // Strings locais para coletar e armazenar dos JTextField
        String cpf = jtxCpf.getText();
        String nome = jtxNome.getText();
        String data_nasc = jtxDataNasc.getText();
        String telefone = jtxTelefone.getText();
        // Comandos condicionais para verificar se campo está vazio ou não
        if ((jtxCpf.getText().isEmpty()) || (jtxNome.getText().isEmpty()) || jtxDataNasc.getText().isEmpty() || jtxTelefone.getText().isEmpty()){
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite todos os campos!", "Erro ao salvar organizador", JOptionPane.ERROR_MESSAGE);
        }
        else {
            // Atribuir valores ao OrganizadorModel
            OrganizadorModel organizador = new OrganizadorModel();
            organizador.setCpf(cpf);
            organizador.setNome(nome);
            organizador.setData_nasc(data_nasc);
            organizador.setTelefone(telefone);               
            // Controller
            OrganizadorController controller = new OrganizadorController();
            // Comandos condicionais para validar se controller funcionou ou não
            if (controller.inserir(organizador)) {
                JOptionPane.showMessageDialog(this, "Organizador inserido com sucesso!", "Sucesso" ,JOptionPane.INFORMATION_MESSAGE);
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }
            else {
                // Tela alertando o usuário sobre o erro
                JOptionPane.showMessageDialog(this, "Erro ao inserir um organizador!", "Erro" ,JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    // Ações válidas quando pressionado o botão jbEditar
    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // Atributos locais para coletar e armazenar dos JTextField
        int Idorganizador = Integer.parseInt(jtxIdOrganizador.getText());
        String cpf = jtxCpf.getText();
        String nome = jtxNome.getText();
        String data_nasc = jtxDataNasc.getText();
        String telefone = jtxTelefone.getText();
        // Comandos condicionais para verificar se campo está vazio ou não
        if ((jtxCpf.getText().isEmpty()) || (jtxNome.getText().isEmpty()) || jtxDataNasc.getText().isEmpty() || jtxTelefone.getText().isEmpty()){
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite todos os campos!", "Erro ao editar organizador", JOptionPane.ERROR_MESSAGE);
        }
        else {
            // Atribuir valores ao OrganizadorModel
            OrganizadorModel organizador = new OrganizadorModel();
            organizador.setIdorganizador(Idorganizador);
            organizador.setCpf(cpf);
            organizador.setNome(nome);
            organizador.setData_nasc(data_nasc);
            organizador.setTelefone(telefone);
            // Controller
            OrganizadorController controller = new OrganizadorController();
            // Comandos condicionais para validar se controller funcionou ou não
            if (controller.editar(organizador)){
                JOptionPane.showMessageDialog(this, "Organizador inserido com sucesso!", "Sucesso" ,JOptionPane.INFORMATION_MESSAGE);
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }
            else {
                // Tela alertando o usuário sobre o erro
                JOptionPane.showMessageDialog(this, "Erro ao inserir um organizador!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    // Ações quando pressionado o botão jbExcluir
    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // OrganizadorModel para excluir o id
        OrganizadorModel organizador = new OrganizadorModel();
        // Comandos condicionais para verificar se campo está vazio ou não
        if (jtxIdOrganizador.getText().isEmpty()) {
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite o código do organizador!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else {
            organizador.setIdorganizador(Integer.parseInt(jtxIdOrganizador.getText()));
            // Controller
            OrganizadorController controller = new OrganizadorController();
            // Comandos condicionais para validar se controller funcionou ou não
            if (controller.excluir(organizador)){
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!", "Sucesso" ,JOptionPane.INFORMATION_MESSAGE);
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }
            else {
                // Tela alertando o usuário sobre o erro
                JOptionPane.showMessageDialog(this, "Erro ao excluir organizador!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    // Ação quando pressionado o botão jbFechar
    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    // Ações quando pressionado o botão jbPesquisar
    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        // OrganizadorModel para pesquisar por id
        OrganizadorModel organizador = new OrganizadorModel();
        // Comandos condicionais para verificar se campo está vazio ou não
        if(jtxIdOrganizador.getText().isEmpty()){
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Preencha o código do organizador!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else {
            organizador.setIdorganizador(Integer.parseInt(jtxIdOrganizador.getText()));
            // Controller
            OrganizadorController controller = new OrganizadorController();
            organizador = controller.selecionar(organizador);
            // Comando condicional para validar se objeto organizador foi encontrado
            if(organizador == null) {
                // Tela alertando que organizador não foi encontrado
                JOptionPane.showMessageDialog(this, "Organizador não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            else {
                // Preencher os campos
                jtxCpf.setText(organizador.getCpf());
                jtxNome.setText(organizador.getNome());
                jtxDataNasc.setText(organizador.getData_nasc());
                jtxTelefone.setText(organizador.getTelefone());
                jbNovo.setEnabled(false);
                jbSalvar.setEnabled(false);
                jbEditar.setEnabled(true);
                jbExcluir.setEnabled(true);
                jtxIdOrganizador.setEditable(false);
                jtxNome.setEditable(true);
                jtxCpf.setEditable(true);
                jtxDataNasc.setEditable(true);
                jtxTelefone.setEditable(true);
            }
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

// Trava eventos do mouse quando clicado em algum objeto do JtOrganizador
    private void jtOrganizadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtOrganizadorMouseClicked
        linha = jtOrganizador.getSelectedRow();
        if(linha != -1){
            jtxIdOrganizador.setText(jtOrganizador.getValueAt(linha,0).toString());
            jtxCpf.setText(jtOrganizador.getValueAt(linha, 1).toString());
            jtxNome.setText(jtOrganizador.getValueAt(linha, 2).toString());
            jtxDataNasc.setText(jtOrganizador.getValueAt(linha, 3).toString());
            jtxTelefone.setText(jtOrganizador.getValueAt(linha, 4).toString());
            jbNovo.setEnabled(false);
            jbSalvar.setEnabled(false);
            jbEditar.setEnabled(true);
            jbExcluir.setEnabled(true);
            jtxIdOrganizador.setEditable(false);
            jtxCpf.setEditable(true);
            jtxNome.setEditable(true);
            jtxDataNasc.setEditable(true);
            jtxTelefone.setEditable(true);
            linha = -1;
        }
    }//GEN-LAST:event_jtOrganizadorMouseClicked
    // Método para preencher JtPrganizador
    private void preencherTabela(){
        OrganizadorController controller = new OrganizadorController();
        ArrayList<OrganizadorModel> lista = controller.selecionarTodos();
        DefaultTableModel modeloTabela = (DefaultTableModel) jtOrganizador.getModel();
        modeloTabela.setRowCount(0);
        // Comando condicional para verificar se foi cadastrado
        if (lista.isEmpty()){
            // Tela alertando que nenhum organizador foi cadastrado
            JOptionPane.showMessageDialog(this, "Nenhum organizador cadastrado!" ,"Erro", JOptionPane.ERROR_MESSAGE);
        }
        else {
            for(OrganizadorModel p: lista) {
                modeloTabela.addRow(new String[]{
                    String.valueOf(p.getIdorganizador()),
                    p.getNome(),
                    p.getCpf(),
                    p.getData_nasc(),
                    p.getTelefone(),
                });
            }
        }
    }
    
    // Método para inicializar os atributos
    private void inicializa(){
        jtxIdOrganizador.setEditable(true);
        jtxCpf.setEditable(false);
        jtxNome.setEditable(false);
        jtxTelefone.setEditable(false);
        jbSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbPesquisar.setEnabled(true);
        jbNovo.setEnabled(true);
    }
    
    // Método para limpar campos
    private void limparCampos(){
        jtxIdOrganizador.setText("");
        jtxCpf.setText("");
        jtxNome.setText("");
        jtxTelefone.setText("");
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlDataNasc;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JPanel jpOrganizador;
    private javax.swing.JTable jtOrganizador;
    private javax.swing.JTextField jtxCpf;
    private javax.swing.JTextField jtxDataNasc;
    private javax.swing.JTextField jtxIdOrganizador;
    private javax.swing.JTextField jtxNome;
    private javax.swing.JTextField jtxTelefone;
    // End of variables declaration//GEN-END:variables
}
