package view;

/**
 *
 * @author caior
 */

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiEvento = new javax.swing.JMenuItem();
        jmiAtividade = new javax.swing.JMenuItem();
        jmiLocal = new javax.swing.JMenuItem();
        jmiOrganizador = new javax.swing.JMenuItem();
        jmiProgramacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        desktop.setBackground(new java.awt.Color(204, 204, 204));
        desktop.setOpaque(false);
        desktop.setPreferredSize(new java.awt.Dimension(817, 617));
        desktop.setLayout(new java.awt.BorderLayout());
        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Cadastro");

        jmiEvento.setText("Evento");
        jmiEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEventoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiEvento);

        jmiAtividade.setText("Atividade");
        jmiAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAtividadeActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAtividade);

        jmiLocal.setText("Local");
        jmiLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLocalActionPerformed(evt);
            }
        });
        jMenu1.add(jmiLocal);

        jmiOrganizador.setText("Organizador");
        jmiOrganizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOrganizadorActionPerformed(evt);
            }
        });
        jMenu1.add(jmiOrganizador);

        jmiProgramacao.setText("Programacao");
        jmiProgramacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProgramacaoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiProgramacao);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // JMenuItem de Programação
    private void jmiProgramacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProgramacaoActionPerformed
        ProgramacaoView programacao = new ProgramacaoView();
        desktop.add(programacao);
        programacao.setVisible(true);
    }//GEN-LAST:event_jmiProgramacaoActionPerformed

    // JMenuItem de Organizador
    private void jmiOrganizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOrganizadorActionPerformed
        OrganizadorView organizador = new OrganizadorView();
        desktop.add(organizador);
        organizador.setVisible(true);
    }//GEN-LAST:event_jmiOrganizadorActionPerformed

    // JMenuItem de Local
    private void jmiLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLocalActionPerformed
        LocalView local = new LocalView();
        desktop.add(local);
        local.setVisible(true);
    }//GEN-LAST:event_jmiLocalActionPerformed

    // JMenuItem de Atividade
    private void jmiAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAtividadeActionPerformed
        AtividadeView atividade = new AtividadeView();
        desktop.add(atividade);
        atividade.setVisible(true);
    }//GEN-LAST:event_jmiAtividadeActionPerformed

    // JMenuItem de Evento
    private void jmiEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEventoActionPerformed
        EventoView evento = new EventoView();
        desktop.add(evento);
        evento.setVisible(true);
    }//GEN-LAST:event_jmiEventoActionPerformed

     /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jmiAtividade;
    private javax.swing.JMenuItem jmiEvento;
    private javax.swing.JMenuItem jmiLocal;
    private javax.swing.JMenuItem jmiOrganizador;
    private javax.swing.JMenuItem jmiProgramacao;
    // End of variables declaration//GEN-END:variables
}
