package view;

// Bibliotecas necessárias
import model.ProgramacaoModel; // Model
import controller.ProgramacaoController; // Controller
import java.util.ArrayList; 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caior
 */

// ProgramacaoeView é um JInternalFrame
public class ProgramacaoView extends javax.swing.JInternalFrame {
    
    // Inicializando componentes
    private int linha = -1; // Atributo contagem para setar valores no JtProgramacao
    public ProgramacaoView() {
        // Métodos
        initComponents();
        preencherTabela();
        inicializa();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpProgramacao = new javax.swing.JPanel();
        jlHoraInicio = new javax.swing.JLabel();
        jlHoraFim = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProgramacao = new javax.swing.JTable();
        jlCodigo = new javax.swing.JLabel();
        jtxHoraFim = new javax.swing.JTextField();
        jtxHoraInicio = new javax.swing.JTextField();
        jtxDataEvento = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jlDataEvento1 = new javax.swing.JLabel();
        jtxIdProgramacao = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();

        setTitle("Programação");
        setPreferredSize(new java.awt.Dimension(497, 418));

        jpProgramacao.setBackground(new java.awt.Color(178, 178, 239));
        jpProgramacao.setForeground(new java.awt.Color(255, 255, 255));

        jlHoraInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlHoraInicio.setForeground(new java.awt.Color(255, 255, 255));
        jlHoraInicio.setText("Hora de Início:");

        jlHoraFim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlHoraFim.setForeground(new java.awt.Color(255, 255, 255));
        jlHoraFim.setText("Hora de Encerramento:");

        jtProgramacao.setBackground(new java.awt.Color(170, 170, 222));
        jtProgramacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtProgramacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtProgramacao.setForeground(new java.awt.Color(255, 255, 255));
        jtProgramacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idprogramacao", "data_evento", "hora_inicio", "hora_fim"
            }
        ));
        jtProgramacao.setToolTipText("");
        jtProgramacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProgramacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProgramacao);

        jlCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jlCodigo.setText("Código:");

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jlDataEvento1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlDataEvento1.setForeground(new java.awt.Color(255, 255, 255));
        jlDataEvento1.setText("Data do Evento:");

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpProgramacaoLayout = new javax.swing.GroupLayout(jpProgramacao);
        jpProgramacao.setLayout(jpProgramacaoLayout);
        jpProgramacaoLayout.setHorizontalGroup(
            jpProgramacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProgramacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProgramacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(jpProgramacaoLayout.createSequentialGroup()
                        .addGroup(jpProgramacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpProgramacaoLayout.createSequentialGroup()
                                .addComponent(jlCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxIdProgramacao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPesquisar))
                            .addGroup(jpProgramacaoLayout.createSequentialGroup()
                                .addComponent(jlDataEvento1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxDataEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpProgramacaoLayout.createSequentialGroup()
                                .addComponent(jlHoraInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpProgramacaoLayout.createSequentialGroup()
                                .addComponent(jlHoraFim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpProgramacaoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jbNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbFechar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpProgramacaoLayout.setVerticalGroup(
            jpProgramacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProgramacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProgramacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo)
                    .addComponent(jtxIdProgramacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpProgramacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDataEvento1)
                    .addComponent(jtxDataEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpProgramacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlHoraInicio)
                    .addComponent(jtxHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpProgramacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlHoraFim)
                    .addComponent(jtxHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpProgramacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir)
                    .addComponent(jbFechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpProgramacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpProgramacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Trava eventos do mouse quando clicado em algum objeto do jtProgramacao
    private void jtProgramacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProgramacaoMouseClicked
        linha = jtProgramacao.getSelectedRow();
        if(linha !=-1){
            jtxIdProgramacao.setText(jtProgramacao.getValueAt(linha, 0).toString());
            jtxDataEvento.setText(jtProgramacao.getValueAt(linha, 1).toString());
            jtxHoraInicio.setText(jtProgramacao.getValueAt(linha, 2).toString());
            jtxHoraFim.setText(jtProgramacao.getValueAt(linha, 3).toString());
            jbNovo.setEnabled(false);
            jbSalvar.setEnabled(false);
            jbEditar.setEnabled(true);
            jbExcluir.setEnabled(true);
            jtxIdProgramacao.setEditable(false);
            jtxDataEvento.setEditable(true);
            jtxHoraInicio.setEditable(true);
            jtxHoraFim.setEditable(true);
            linha = -1;
    }//GEN-LAST:event_jtProgramacaoMouseClicked
    }
    
    // Ações válidas quando pressionado o botão jbNovo
    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbSalvar.setEnabled(true);
        jtxIdProgramacao.setEditable(true);
        jtxDataEvento.setEditable(true);
        jtxHoraInicio.setEditable(true);
        jtxHoraFim.setEditable(true);
    }//GEN-LAST:event_jbNovoActionPerformed

    // Ações válidas quando pressionado o botão jbSalvar
    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // Strings para coletar e armazenar JTextField
        String data_evento = jtxDataEvento.getText();
        String hora_inicio = jtxHoraInicio.getText();
        String hora_fim = jtxHoraFim.getText();
        // Comandos condicionais para verificar se campo está vazio ou não
        if((jtxDataEvento.getText().isEmpty())||(jtxHoraInicio.getText().isEmpty())||(jtxHoraFim.getText().isEmpty()))
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite todos os campos!", "Erro ao salvar programação", JOptionPane.ERROR_MESSAGE);
        else{
            // Atribuir valores ao ProgramacaoModel
            ProgramacaoModel programacao = new ProgramacaoModel();
            programacao.setData_evento(data_evento);
            programacao.setHora_inicio(hora_inicio);
            programacao.setHora_fim(hora_fim);
            // Controller
            ProgramacaoController controller = new ProgramacaoController();
            // Comandos condicionais para validar se controller funcionou ou não
            if(controller.inserir(programacao)){
                JOptionPane.showMessageDialog(this, "Programação inserida com sucesso!", "Sucesso" ,JOptionPane.INFORMATION_MESSAGE);
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }
            else {
                // Tela alertando o usuário sobre o erro
                JOptionPane.showMessageDialog(this, "Erro ao inserir uma programação!", "Retorno BD", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    // Ações válidas quando pressionado o botão jbEditar
    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // Atributos locais para coletar e armazenar dos JTextField
        int Idprogramacao = Integer.parseInt(jtxIdProgramacao.getText());
        String data_evento = jtxDataEvento.getText();
        String hora_inicio = jtxHoraInicio.getText();
        String hora_fim = jtxHoraFim.getText();
        // Comandos condicionais para verificar se campo está vazio ou não
        if((data_evento.isEmpty())||(hora_inicio.isEmpty())||(hora_fim.isEmpty())) 
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite todos os campos!", "Erro ao editar programação", JOptionPane.ERROR_MESSAGE);        
        else{
            // Atribuir valores ao ProgramacaoModel
            ProgramacaoModel programacao = new ProgramacaoModel();
            programacao.setIdprogramacao(Idprogramacao);
            programacao.setData_evento(data_evento);
            programacao.setHora_inicio(hora_inicio);
            programacao.setHora_fim(hora_fim);
            // Controller
            ProgramacaoController controller = new ProgramacaoController();
            // Comandos condicionais para validar se controller funcionou ou não
            if(controller.editar(programacao)){
                JOptionPane.showMessageDialog(this, "Atualização com sucesso!");
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }
            else{
                // Tela alertando o usuário sobre o erro
                JOptionPane.showMessageDialog(this, "Erro ao editar programação!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    // Ações quando pressionado o botão jbExcluir
    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // ProgramaçãoModel para excluir o id
        ProgramacaoModel programacao = new ProgramacaoModel();
        // Comandos condicionais para verificar se campo está vazio ou não
        if(jtxIdProgramacao.getText().isEmpty()){ // Se campo estiver vazio
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Digite o código da programação!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            programacao.setIdprogramacao(Integer.parseInt(jtxIdProgramacao.getText()));
            // Controller
            ProgramacaoController controller = new ProgramacaoController();
            // Comandos condicionais para validar se controller funcionou ou não
            if(controller.excluir(programacao)){
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!", "Sucesso" ,JOptionPane.INFORMATION_MESSAGE);
                // Chamar métodos
                limparCampos();
                inicializa();
                preencherTabela();
            }
            else {
                // Tela alertando o usuário sobre o erro  
                JOptionPane.showMessageDialog(this, "Erro ao excluir programação!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    // Ação quando pressionado o botão jbFechar
    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    // Ações quando pressionado o botão jbPesquisar
    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        // ParticipanteModel para pesquisar por id
        ProgramacaoModel programacao = new ProgramacaoModel();
        // Comandos condicionais para verificar se campo está vazio ou não
        if(jtxIdProgramacao.getText().isEmpty()) {
            // Tela alertando o usuário sobre o erro
            JOptionPane.showMessageDialog(this, "Preencha o código da programação!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            programacao.setIdprogramacao(Integer.parseInt(jtxIdProgramacao.getText()));
            // Controller
            ProgramacaoController controller = new ProgramacaoController();
            programacao = controller.selecionar(programacao);
            // Comando condicional para validar se objeto programação foi encontrado
            if(programacao == null) {
                // Tela alertando que programação não foi encontrada
                JOptionPane.showMessageDialog(this, "Programação não encontrada!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            else {
                // Preencher os campos
                jtxDataEvento.setText(programacao.getData_evento());
                jtxHoraInicio.setText(programacao.getHora_inicio());
                jtxHoraFim.setText(programacao.getHora_fim());
                jbNovo.setEnabled(false);
                jbSalvar.setEnabled(false);
                jbEditar.setEnabled(true);
                jbExcluir.setEnabled(true);
                jtxIdProgramacao.setEditable(false);
                jtxDataEvento.setEditable(true);
                jtxHoraInicio.setEditable(true);
                jtxHoraFim.setEditable(true);
            }
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed
    
    // Método para preencher JtProgramacao
    private void preencherTabela(){
        ProgramacaoController controller = new ProgramacaoController();
        ArrayList<ProgramacaoModel> lista = controller.selecionarTodos();
        DefaultTableModel modeloTabela = (DefaultTableModel) jtProgramacao.getModel();
        modeloTabela.setRowCount(0);
        // Comando condicional para verificar se foi cadastrado
        if(lista.isEmpty()) {
            // Tela alertando que nenhuma programação foi cadastrada
            JOptionPane.showMessageDialog(this, "Nenhuma programação cadastrada!","Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            for(ProgramacaoModel p: lista){
                modeloTabela.addRow(new String[]{
                    String.valueOf(p.getIdprogramacao()),
                    p.getData_evento(),
                    p.getHora_inicio(),
                    p.getHora_fim()
                });
            }
        }
    }
    
    // Método para inicializar os atributos
    private void inicializa(){
        jtxIdProgramacao.setEditable(true);
        jtxDataEvento.setEditable(false);
        jtxHoraInicio.setEditable(false);
        jtxHoraFim.setEditable(false);
        jbSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbPesquisar.setEnabled(true);
        jbNovo.setEnabled(true);
    }
    
    // Método para limpar campos
    private void limparCampos(){
        jtxIdProgramacao.setText("");
        jtxDataEvento.setText("");
        jtxHoraInicio.setText("");
        jtxHoraFim.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlDataEvento1;
    private javax.swing.JLabel jlHoraFim;
    private javax.swing.JLabel jlHoraInicio;
    private javax.swing.JPanel jpProgramacao;
    private javax.swing.JTable jtProgramacao;
    private javax.swing.JTextField jtxDataEvento;
    private javax.swing.JTextField jtxHoraFim;
    private javax.swing.JTextField jtxHoraInicio;
    private javax.swing.JTextField jtxIdProgramacao;
    // End of variables declaration//GEN-END:variables
}
